namespace Enums
{
	public enum GameStates
	{
		INITIALIZE_STATE,
		LOGGING_IN_STATE,
		SELECTION_STATE,
		START_STATE,
		GAME_OVER_STATE
	}
	public enum ROOM_EVENT
	{
		LOGGED_IN,
		ON_ROOM_LIST_UPDATE,
		ON_LEFT_LOBBY,
		ON_CREATE_ROOM_FAILED,
		ON_JOIN_ROOM,
		ON_JOIN_ROOM_FAILED,
		ON_JOIN_RANDOM_ROOM_FAILED,
		ON_JOINED_ROOM,
		ON_LEFT_ROOM,
		ON_PLAYER_ENTERED_ROOM,
		ON_MASTER_CLIENT_SWITCHED,
		IS_PLAYER_READY
	}
	public enum GAMEPLAY_EVENT
	{
		INITIALIZE = 0,
		START,
		TIME_EXPIRED,
		PLAYER_RESPAWN,
		GAMEOVER
	}

	public enum EVENT_TYPE
	{
		NONE,
		SCENE_EVENT,
		UI_EVENT
	}
}
